---
title: "Further exploration of goseq analysis resutls"
author: "Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 80)
```

Summarize GOseq enrichment analysis results. 

# Setup

## Load R libraries
```{r load_libraries, message=FALSE, warning=FALSE}
library(data.table)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(cowplot)
library(flextable)

library(tidyr)
theme_set(theme_classic())
```

# Check enrichment of gene sets

## Read in goseq results

```{r}
cell_type_name = "CD8T"
graph_weight = "2.0"
file_tag = sprintf("%s_%s", cell_type_name, graph_weight)
res1 = readRDS(sprintf("output/gene_set_enrichments_%s.RDS", file_tag))

if(is.null(res1)){ next }

gene_sets = names(res1)
      
df_go = NULL

for(gset1 in gene_sets){
  res_g1 = res1[[gset1]]

  df1 = data.frame(gene_set = rep(gset1, length(res_g1)))
  df1$type = names(res_g1)
  df1$category = sapply(res_g1, function(x){
    x=x[x$over_represented_pvalue < 0.05,]; x$category[1]})
  df1$FDR = sapply(res_g1, function(x){
    x=x[x$over_represented_pvalue < 0.05,]; x$FDR[1]})
  
  df_go = rbind(df_go, df1)
}

df_go$FDR = as.character(signif(df_go$FDR, 3))
ft = flextable(df_go)
ft = width(ft, width = c(1.0, 1.0, 4, 1.0))
ft
```

## Read in gene sets

```{r}
assayed_genes = scan(sprintf("output/gene_list_%s.txt", file_tag), 
                     what = character(), sep="\n")

gene_sets = scan(sprintf("output/name_s_%s.txt", file_tag), 
                 what = character(), sep="\n")

gene_sets = sapply(gene_sets, strsplit, split=",")
n_genes   = sapply(gene_sets, length)
names(n_genes) = NULL
summary(n_genes)
length(n_genes)
sum(n_genes)
```

## Read in gene information. 
```{r}
genes = fread("../Annotation/gencode_v44_basic_gene_info.tsv.gz")
dim(genes)
genes[1:2,]

gene_set1 = gene_sets[[1]]
gene_set1

table(gene_set1 %in% genes$hgnc_symbol)
setdiff(gene_set1, genes$hgnc_symbol)
gene_set1[gene_set1 == "C6orf203"] = "MTRES1"
gene_set1[gene_set1 == "CCDC109B"] = "MCUB"

table(gene_set1 %in% genes$hgnc_symbol)

gene_anno1 = genes[match(gene_set1, genes$hgnc_symbol),]
dim(gene_anno1)
gene_anno1[1:2,]

gene_anno1$description = sub(" \\[.*", "", gene_anno1$description)
gene_anno1 = gene_anno1[order(gene_anno1$hgnc_symbol),]
ft = flextable(gene_anno1[,c("hgnc_symbol", "chr", "description")])
ft = width(ft, width = c(1.0, 1.0, 4.5))
ft
```

# Session information
```{r}
gc()

sessionInfo()
```

