---
title: "Check genes associated with case-control status"
author: "Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
params:
  cell_type_name: "cd4"
  graph_weight: "2.0" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 80)
```


# Setup

## Load R libraries
```{r load_libraries, message=FALSE, warning=FALSE}
library(data.table)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(limma)
library(stringr)
library(Matrix)
library(gplots)
library(zellkonverter)
library(pROC)
library(doParallel)
library(foreach)
library(SummarizedExperiment)
library(reticulate)

theme_set(theme_classic())

cell_type_name = params$cell_type_name
graph_weight = params$graph_weight

cell_type_name
graph_weight

nCore = 10

registerDoParallel(cores=nCore)
options(mc.cores=nCore)
getOption("mc.cores")

np = import("numpy")
```

# Read in data


## Read in assignment matrix S

```{r fig.width=3, fig.height=3}
file_tag = sprintf("%s_BL_%s", cell_type_name, graph_weight)

npy_array = np$load(sprintf("output/train_s_%s.npy", file_tag))
s_mat = data.matrix(npy_array)
dim(s_mat)
s_mat[1:2,1:3]

colSums(s_mat > 0.5)
colSums(s_mat > 0.8)

v_s = c(s_mat)
summary(v_s)
table(v_s <= 0.1)

df1 = data.frame(score = v_s[v_s > 0.1])
ggplot(data = df1, aes(x = score)) +
  geom_histogram(breaks = seq(0.1, 1, by=0.05), fill = "skyblue", 
                 color = "darkblue", alpha = 0.7)
```


## Read in gene expression data

```{r fig.width=4.5, fig.height=3}
edat = readMM(sprintf("~/Dropbox/COVID_data/Su_2020/gex_%s_BL.mtx.gz", cell_type_name))
dim(edat)
edat[1:2,1:3]

genes_all = scan(sprintf("gex_%s_BL_genes.txt", cell_type_name), what=character())
length(genes_all)

genes2use = scan(sprintf("output/gene_list_%s.txt", file_tag), what=character())
length(genes2use)

cells_all = fread(sprintf("cell_info_%s_BL.csv", cell_type_name))
dim(cells_all)
cells_all[1:2,]

test_reduced = readH5AD(sprintf("output/test_reduced_%s.h5ad", file_tag))
class(test_reduced)
dim(test_reduced)

cell_info = colData(test_reduced)
dim(cell_info)
cell_info[1:2,]

w_genes = match(genes2use, genes_all)
w_cells = match(cell_info$barcode, cells_all$V1)

# now the edata are gene expression data in testing set
edat = edat[w_cells,]
dim(edat)

rd = rowSums(edat)
df1 = data.frame(read_depth = rd, group = cell_info$cell_type)
tapply(df1$read_depth, df1$group, summary)

ggplot(data = df1, aes(x = read_depth)) +
  geom_histogram(bins=20, fill = "skyblue", color = "darkblue", alpha = 0.7)

ggplot(data = df1, aes(x = read_depth)) + 
  geom_density(aes(color=group, fill=group), alpha = 0.5)

percent_zero_per_gene = colMeans(edat == 0)
gene_group = rep("not-selected", ncol(edat))
gene_group[w_genes] = "selected"

df2 = data.frame(percent_zero_per_gene = percent_zero_per_gene, 
                 group = gene_group)
tapply(df2$percent_zero_per_gene, df2$group, summary)

ggplot(data = df2, aes(x = percent_zero_per_gene)) + 
  geom_density(aes(color=group, fill=group), alpha = 0.5)
```

## Evaluate AUC for each of the selected genes.

```{r fig.width=3, fig.height=3}

table(cell_info$cell_type)

y_true = cell_info$cell_type
table(y_true)

auc_vals = foreach(wg1 = w_genes, .combine = "c") %dopar% {
  y1 = edat[,wg1]
  auc1 = auc(roc(y_true, y1, levels=c("mild", "severe"), direction = "<"))
  as.numeric(auc1)
}

summary(auc_vals)
```

## Double check the data of reduced representation

```{r fig.width=3, fig.height=3}
df1 = data.frame(gene=genes2use, auc=auc_vals, gene_set = 0)

for(k in 1:ncol(s_mat)){
  genes_k = which(s_mat[,k] > 0.8)
  if(length(genes_k) > 0) df1$gene_set[genes_k] = k
}

tapply(df1$auc, df1$gene_set, summary)

rdat = assay(test_reduced, "X")
dim(rdat)

# Regenerate the reduced data matrix to check consistency

rd = rowSums(edat)
ndat = log(1 + (edat)/rd*1e4)
dim(ndat)
ndat[1:4,1:5]

rdat_0 = as.matrix(t(s_mat) %*% t(ndat[,w_genes]))
dim(rdat_0)

rdat[1:2,1:3]
rdat_0[1:2,1:3]

summary(c(rdat - rdat_0))
```

## Check the AUC of each reduced component and its distribution. 

```auc_r``` is the AUC for the 
```{r fig.width=5, fig.height=3}

auc_r = foreach(i = 1:nrow(rdat), .combine = "c") %dopar% {
  y1 = rdat[i,]
  auc1 = auc(roc(y_true, y1, levels=c("mild", "severe"), direction = "<"))
  as.numeric(auc1)
}

summary(auc_vals)
summary(auc_r)

df_r = data.frame(component = 1:40, auc=auc_r, n_genes = colSums(s_mat > 0.8))
df_r[["auc_genes"]] = NA

ggplot(data = df_r, aes(x=component, y=auc)) + 
  geom_point() + geom_text(data = subset(df_r, n_genes > 0),
                  aes(label = n_genes), hjust = -0.5) + 
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "red") + 
  geom_vline(xintercept = seq(5,40,by=5), color = "grey")

rdf = data.frame(t(rdat))
names(rdf) = paste0("S", 1:40)
rdf[["group"]] = y_true

ggplot(data=rdf, aes(x = S9, fill = group)) +
        geom_density(alpha=0.5)

ggplot(data=rdf, aes(x = S11, fill = group)) +
        geom_density(alpha=0.5)

ggplot(data=rdf, aes(x = S16, fill = group)) +
        geom_density(alpha=0.5)

ggplot(data=rdf, aes(x = S20, fill = group)) +
        geom_density(alpha=0.5)

ggplot(data=rdf, aes(x = S30, fill = group)) +
        geom_density(alpha=0.5)

ggplot(data=rdf, aes(x = colSums(rdat), fill = group)) +
        geom_density(alpha=0.5) + xlab("sum of reduced representation") 

ggplot(data=rdf, aes(x = rowSums(edat[,w_genes]), fill = group)) +
        geom_density(alpha=0.5) + xlab("read-depth of selected genes") 

```

# Session information

```{r}
gc()

sessionInfo()
```

